import { NextRequest, NextResponse } from "next/server";
import { curateInsights } from "@/lib/memory-ai/curator";
import { runScheduledAnalysis } from "@/lib/memory-ai/scheduler";

/**
 * GET /api/memory-ai
 * Returns curated insights and recommendations
 */
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const action = searchParams.get("action");

    if (action === "curate") {
      // Run full curation
      const insights = await curateInsights();
      return NextResponse.json({ insights });
    }

    if (action === "recommendations") {
      // Get daily recommendations only
      const insights = await curateInsights();
      return NextResponse.json({
        recommendations: insights.dailyRecommendation,
      });
    }

    if (action === "weaknesses") {
      // Get weakness report only
      const insights = await curateInsights();
      return NextResponse.json({
        weaknesses: insights.weaknesses,
      });
    }

    if (action === "insights") {
      // Get unifying insights only
      const insights = await curateInsights();
      return NextResponse.json({
        insights: insights.unifyingInsights,
      });
    }

    // Default: return full summary
    const insights = await curateInsights();
    return NextResponse.json({
      summary: {
        strengths: insights.strengths,
        weaknesses: insights.weaknesses,
        unifyingInsights: insights.unifyingInsights,
        dailyRecommendation: insights.dailyRecommendation,
        autoGeneratedCards: insights.autoGeneratedCards,
        totalAnalysis: insights.totalAnalysis,
      },
    });
  } catch (error: any) {
    console.error("Error in memory-ai API:", error);
    return NextResponse.json(
      { error: `Failed to curate insights: ${error.message}` },
      { status: 500 }
    );
  }
}

/**
 * POST /api/memory-ai
 * Triggers background analysis and updates
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const action = body.action || "analyze";

    if (action === "analyze") {
      // Run scheduled analysis
      const result = await runScheduledAnalysis();
      return NextResponse.json({
        success: true,
        message: "Analysis completed",
        result,
      });
    }

    if (action === "curate") {
      // Run full curation
      const insights = await curateInsights();
      return NextResponse.json({
        success: true,
        insights,
      });
    }

    return NextResponse.json(
      { error: "Invalid action" },
      { status: 400 }
    );
  } catch (error: any) {
    console.error("Error in memory-ai POST:", error);
    return NextResponse.json(
      { error: `Failed to process request: ${error.message}` },
      { status: 500 }
    );
  }
}
