"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { motion } from "framer-motion";
import { Main } from "@/components/Main";
import { BrutalistCard } from "@/components/BrutalistCard";
import { OrangeAction } from "@/components/core/OrangeAction";
import { MemoriaShell } from "@/components/Memoria/MemoriaShell";

interface WeaknessReport {
  lowEaseCards: Array<{
    id: string;
    title: string;
    ease: number;
    errorRate: number;
    recommendation: string;
  }>;
  fallacyErrors: Array<{
    type: string;
    count: number;
    examples: string[];
    recommendation: string;
  }>;
  puzzleMistakes: Array<{
    puzzleId: string;
    type: string;
    attempts: number;
    recommendation: string;
  }>;
  weakConcepts: Array<{
    concept: string;
    sources: string[];
    frequency: number;
    recommendation: string;
  }>;
}

interface UnifyingInsight {
  id: string;
  title: string;
  description: string;
  sources: string[];
  relatedCards: string[];
  confidence: number;
}

interface DailyRecommendation {
  concepts: Array<{
    cardId: string;
    title: string;
    reason: string;
  }>;
  chapters: Array<{
    bookId: string;
    chapterId: string;
    title: string;
    reason: string;
  }>;
  puzzles: Array<{
    puzzleId: string;
    type: string;
    reason: string;
  }>;
  generatedAt: string;
}

interface InsightSummary {
  strengths: string[];
  weaknesses: WeaknessReport;
  unifyingInsights: UnifyingInsight[];
  dailyRecommendation: DailyRecommendation;
  autoGeneratedCards: number;
  totalAnalysis: {
    cardsAnalyzed: number;
    highlightsAnalyzed: number;
    chaptersAnalyzed: number;
    notesAnalyzed: number;
  };
}

export default function InsightsPage() {
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [summary, setSummary] = useState<InsightSummary | null>(null);
  const [refreshing, setRefreshing] = useState(false);

  useEffect(() => {
    loadInsights();
  }, []);

  const loadInsights = async () => {
    try {
      setLoading(true);
      const response = await fetch("/api/memory-ai");
      if (response.ok) {
        const data = await response.json();
        setSummary(data.summary);
      }
    } catch (error) {
      console.error("Error loading insights:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleRefresh = async () => {
    setRefreshing(true);
    try {
      const response = await fetch("/api/memory-ai", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ action: "curate" }),
      });
      if (response.ok) {
        const data = await response.json();
        setSummary(data.insights);
      }
    } catch (error) {
      console.error("Error refreshing insights:", error);
    } finally {
      setRefreshing(false);
    }
  };

  if (loading) {
    return (
      <Main>
        <MemoriaShell>
          <div className="flex items-center justify-center min-h-screen">
            <div className="text-center">
              <div
                className="font-serif text-xl mb-4"
                style={{ color: "#C8B68D" }}
              >
                Analyzing Your Memory...
              </div>
              <div
                className="font-mono text-sm opacity-60"
                style={{ color: "#C8B68D" }}
              >
                Curating insights from your learning data...
              </div>
            </div>
          </div>
        </MemoriaShell>
      </Main>
    );
  }

  if (!summary) {
    return (
      <Main>
        <MemoriaShell>
          <BrutalistCard borderWidth="1.5" className="p-6">
            <div className="font-mono text-sm text-muted-foreground">
              Unable to load insights. Please try again.
            </div>
            <OrangeAction onClick={loadInsights} className="mt-4">
              Retry
            </OrangeAction>
          </BrutalistCard>
        </MemoriaShell>
      </Main>
    );
  }

  return (
    <Main>
      <MemoriaShell>
        <div className="relative z-10 min-h-screen p-6">
          <div className="max-w-6xl mx-auto">
            {/* Header */}
            <motion.div
              initial={{ opacity: 0, y: -20 }}
              animate={{ opacity: 1, y: 0 }}
              className="mb-8"
            >
              <div className="flex items-center justify-between mb-4">
                <div>
                  <h1
                    className="font-serif text-4xl mb-2 engraved engrave"
                    style={{ color: "#C8B68D" }}
                  >
                    Insight Curator
                  </h1>
                  <p
                    className="font-mono text-sm opacity-60"
                    style={{ color: "#C8B68D" }}
                  >
                    AI-powered analysis of your learning patterns
                  </p>
                </div>
                <OrangeAction
                  onClick={handleRefresh}
                  disabled={refreshing}
                  className="ml-4"
                >
                  {refreshing ? "Analyzing..." : "Refresh Analysis"}
                </OrangeAction>
              </div>
            </motion.div>

            {/* Analysis Summary */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
              className="mb-8"
            >
              <BrutalistCard borderWidth="1.5" className="p-6 floating-panel">
                <div className="font-serif text-xl mb-4 engraved">
                  Analysis Summary
                </div>
                <div className="font-mono text-sm grid grid-cols-2 md:grid-cols-4 gap-4">
                  <div>
                    <div className="text-muted-foreground mb-1">
                      Cards Analyzed
                    </div>
                    <div className="font-semibold">
                      {summary.totalAnalysis.cardsAnalyzed}
                    </div>
                  </div>
                  <div>
                    <div className="text-muted-foreground mb-1">Highlights</div>
                    <div className="font-semibold">
                      {summary.totalAnalysis.highlightsAnalyzed}
                    </div>
                  </div>
                  <div>
                    <div className="text-muted-foreground mb-1">Chapters</div>
                    <div className="font-semibold">
                      {summary.totalAnalysis.chaptersAnalyzed}
                    </div>
                  </div>
                  <div>
                    <div className="text-muted-foreground mb-1">New Cards</div>
                    <div className="font-semibold text-[#b29b68]">
                      {summary.autoGeneratedCards}
                    </div>
                  </div>
                </div>
              </BrutalistCard>
            </motion.div>

            {/* Strengths */}
            {summary.strengths.length > 0 && (
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2 }}
                className="mb-8"
              >
                <div className="font-serif text-2xl mb-4 engraved engrave">
                  Strengths
                </div>
                <div className="space-y-3">
                  {summary.strengths.map((strength, index) => (
                    <motion.div
                      key={index}
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 0.3 + index * 0.05 }}
                    >
                      <BrutalistCard
                        borderWidth="1"
                        className="p-4 floating-panel"
                      >
                        <div className="font-mono text-sm">{strength}</div>
                      </BrutalistCard>
                    </motion.div>
                  ))}
                </div>
              </motion.div>
            )}

            {/* Weaknesses */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 }}
              className="mb-8"
            >
              <div className="font-serif text-2xl mb-4 engraved engrave">
                Weakness Report
              </div>

              {/* Low Ease Cards */}
              {summary.weaknesses.lowEaseCards.length > 0 && (
                <div className="mb-6">
                  <div className="font-serif text-lg mb-3 engraved">
                    Struggling Concepts
                  </div>
                  <div className="space-y-3">
                    {summary.weaknesses.lowEaseCards.map((card, index) => (
                      <motion.div
                        key={card.id}
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: 0.4 + index * 0.05 }}
                      >
                        <BrutalistCard
                          borderWidth="1"
                          className="p-4 floating-panel"
                        >
                          <div className="flex items-start justify-between mb-2">
                            <div className="font-serif text-base engraved">
                              {card.title}
                            </div>
                            <div className="font-mono text-xs text-muted-foreground">
                              Ease: {card.ease.toFixed(2)}
                            </div>
                          </div>
                          <div className="font-mono text-xs text-muted-foreground">
                            {card.recommendation}
                          </div>
                        </BrutalistCard>
                      </motion.div>
                    ))}
                  </div>
                </div>
              )}

              {/* Fallacy Errors */}
              {summary.weaknesses.fallacyErrors.length > 0 && (
                <div className="mb-6">
                  <div className="font-serif text-lg mb-3 engraved">
                    Reasoning Errors
                  </div>
                  <div className="space-y-3">
                    {summary.weaknesses.fallacyErrors.map((error, index) => (
                      <motion.div
                        key={error.type}
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: 0.5 + index * 0.05 }}
                      >
                        <BrutalistCard
                          borderWidth="1"
                          className="p-4 floating-panel"
                        >
                          <div className="flex items-start justify-between mb-2">
                            <div className="font-serif text-base engraved">
                              {error.type}
                            </div>
                            <div className="font-mono text-xs text-muted-foreground">
                              {error.count} occurrences
                            </div>
                          </div>
                          <div className="font-mono text-xs text-muted-foreground">
                            {error.recommendation}
                          </div>
                        </BrutalistCard>
                      </motion.div>
                    ))}
                  </div>
                </div>
              )}

              {/* Weak Concepts */}
              {summary.weaknesses.weakConcepts.length > 0 && (
                <div className="mb-6">
                  <div className="font-serif text-lg mb-3 engraved">
                    Weak Concepts
                  </div>
                  <div className="space-y-3">
                    {summary.weaknesses.weakConcepts.map((concept, index) => (
                      <motion.div
                        key={concept.concept}
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: 0.6 + index * 0.05 }}
                      >
                        <BrutalistCard
                          borderWidth="1"
                          className="p-4 floating-panel"
                        >
                          <div className="font-serif text-base mb-2 engraved">
                            {concept.concept}
                          </div>
                          <div className="font-mono text-xs text-muted-foreground mb-2">
                            Appears in {concept.frequency} sources
                          </div>
                          <div className="font-mono text-xs text-muted-foreground">
                            {concept.recommendation}
                          </div>
                        </BrutalistCard>
                      </motion.div>
                    ))}
                  </div>
                </div>
              )}
            </motion.div>

            {/* Daily Recommendations */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.4 }}
              className="mb-8"
            >
              <div className="font-serif text-2xl mb-4 engraved engrave">
                Daily Recommendations
              </div>

              {/* Recommended Concepts */}
              {summary.dailyRecommendation.concepts.length > 0 && (
                <div className="mb-6">
                  <div className="font-serif text-lg mb-3 engraved">
                    Study These 3 Concepts
                  </div>
                  <div className="space-y-3">
                    {summary.dailyRecommendation.concepts.map(
                      (concept, index) => (
                        <motion.div
                          key={concept.cardId}
                          initial={{ opacity: 0, x: -20 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: 0.5 + index * 0.05 }}
                        >
                          <BrutalistCard
                            borderWidth="1"
                            className="p-4 floating-panel"
                          >
                            <div className="font-serif text-base mb-2 engraved">
                              {concept.title}
                            </div>
                            <div className="font-mono text-xs text-muted-foreground">
                              {concept.reason}
                            </div>
                            <OrangeAction
                              onClick={() =>
                                router.push(`/memoria?card=${concept.cardId}`)
                              }
                              className="mt-3"
                            >
                              Study Now
                            </OrangeAction>
                          </BrutalistCard>
                        </motion.div>
                      )
                    )}
                  </div>
                </div>
              )}

              {/* Recommended Chapters */}
              {summary.dailyRecommendation.chapters.length > 0 && (
                <div className="mb-6">
                  <div className="font-serif text-lg mb-3 engraved">
                    Review These Chapters
                  </div>
                  <div className="space-y-3">
                    {summary.dailyRecommendation.chapters.map(
                      (chapter, index) => (
                        <motion.div
                          key={`${chapter.bookId}-${chapter.chapterId}`}
                          initial={{ opacity: 0, x: -20 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: 0.6 + index * 0.05 }}
                        >
                          <BrutalistCard
                            borderWidth="1"
                            className="p-4 floating-panel"
                          >
                            <div className="font-serif text-base mb-2 engraved">
                              {chapter.title}
                            </div>
                            <div className="font-mono text-xs text-muted-foreground mb-2">
                              {chapter.reason}
                            </div>
                            <OrangeAction
                              onClick={() =>
                                router.push(
                                  `/bibliotheca/${chapter.bookId}?chapter=${chapter.chapterId}`
                                )
                              }
                              className="mt-3"
                            >
                              Open Chapter
                            </OrangeAction>
                          </BrutalistCard>
                        </motion.div>
                      )
                    )}
                  </div>
                </div>
              )}

              {/* Recommended Puzzles */}
              {summary.dailyRecommendation.puzzles.length > 0 && (
                <div className="mb-6">
                  <div className="font-serif text-lg mb-3 engraved">
                    Practice These Puzzle Types
                  </div>
                  <div className="space-y-3">
                    {summary.dailyRecommendation.puzzles.map(
                      (puzzle, index) => (
                        <motion.div
                          key={puzzle.puzzleId}
                          initial={{ opacity: 0, x: -20 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: 0.7 + index * 0.05 }}
                        >
                          <BrutalistCard
                            borderWidth="1"
                            className="p-4 floating-panel"
                          >
                            <div className="font-serif text-base mb-2 engraved">
                              {puzzle.type} Puzzles
                            </div>
                            <div className="font-mono text-xs text-muted-foreground mb-2">
                              {puzzle.reason}
                            </div>
                            <OrangeAction
                              onClick={() =>
                                router.push(`/laboratorivm?type=${puzzle.type}`)
                              }
                              className="mt-3"
                            >
                              Practice Now
                            </OrangeAction>
                          </BrutalistCard>
                        </motion.div>
                      )
                    )}
                  </div>
                </div>
              )}
            </motion.div>

            {/* Unifying Insights */}
            {summary.unifyingInsights.length > 0 && (
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.5 }}
                className="mb-8"
              >
                <div className="font-serif text-2xl mb-4 engraved engrave">
                  Unifying Insights
                </div>
                <div className="space-y-4">
                  {summary.unifyingInsights.map((insight, index) => (
                    <motion.div
                      key={insight.id}
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: 0.6 + index * 0.1 }}
                    >
                      <BrutalistCard
                        borderWidth="1.5"
                        className="p-6 floating-panel"
                      >
                        <div className="font-serif text-xl mb-3 engraved">
                          {insight.title}
                        </div>
                        <div className="font-mono text-sm text-muted-foreground mb-4">
                          {insight.description}
                        </div>
                        <div className="flex items-center justify-between">
                          <div className="font-mono text-xs text-muted-foreground">
                            Confidence: {Math.round(insight.confidence * 100)}%
                          </div>
                          <div className="font-mono text-xs text-muted-foreground">
                            {insight.relatedCards.length} related cards
                          </div>
                        </div>
                      </BrutalistCard>
                    </motion.div>
                  ))}
                </div>
              </motion.div>
            )}

            {/* Back Button */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.6 }}
              className="mt-8"
            >
              <OrangeAction onClick={() => router.push("/memoria")}>
                Back to Memoria
              </OrangeAction>
            </motion.div>
          </div>
        </div>
      </MemoriaShell>
    </Main>
  );
}
